### ISSUE TITLE
医院详情-表单提交功能

### ISSUE THREAD

**Issue by liuyiqi123** [wsfront/wh-ncov-front#71]
1. 从info的item拿数据，或ElementUI v-model
2. 暂时忽略电话不可用情况
3. 仅完成提交按钮的功能：数据处理，发送

**Comment by demongodYY** [comment]
测试时，发现修改医院的信息没起作用，只有电话信息可以修改
![image](https://user-images.githubusercontent.com/17036920/75005020-01d1ff80-54a8-11ea-9456-717cfe845774.png)
![image](https://user-images.githubusercontent.com/17036920/75005023-04345980-54a8-11ea-8516-94e45d7176a8.png)
![image](https://user-images.githubusercontent.com/17036920/75005028-0991a400-54a8-11ea-90d7-974453fabd8b.png)
